services:
  ws.mysql:
    build:
      context: ws.mysql/
      dockerfile: Dockerfile
    container_name: ws.mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    restart: always
    volumes:
      - './ws.mysql/db:/var/lib/mysql'
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 30s
      retries: 10
    networks:
      - ws_network

  ws.dbviewer:
    build:
      context: ws.dbviewer/
      dockerfile: Dockerfile
    container_name: ws.dbviewer
    restart: unless-stopped
    depends_on:
      ws.mysql:
        condition: service_healthy
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      ADMINER_DESIGN: ${ADMINER_DESIGN}
    networks:
      - ws_network

networks:
  ws_network:
